Update _index.ja_jp.md
xerosbaseball/terms pull request #56
Opened 2022-11-01 10:05 UTC by Xeros18

2022-11-01 10:14 UTC, susumutomita commented on content/role/_index.ja_jp.md
> +##概要
ここスペース入れないとだめ
## 概要
とする

2022-11-01 10:14 UTC, susumutomita commented on content/role/_index.ja_jp.md
> +| 試合球管理     | 毎試合 | 新品のボールを購入し、試合に持参する。              |
下に埋め込みリンクあるのだからリンクにしたほうがいいです。

2022-11-01 10:15 UTC, susumutomita requested changes
2点フィードバック
- 概要が崩れている
- テーブルにリンクつけてほしい

2022-11-02 10:57 UTC, closed without merging

2022-11-02 11:03 UTC, Xeros18 commented on content/role/_index.ja_jp.md
> +##概要
修正します

2022-11-02 11:03 UTC, Xeros18 commented on content/role/_index.ja_jp.md
> +| 試合球管理     | 毎試合 | 新品のボールを購入し、試合に持参する。              |
修正します